import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Konreg PDRB Sumatera 2024",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <html lang="en">{children}</html>;
}
