import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Konreg PDRB Sumatera 2024",
  // description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "700", "800"],
  display: "swap",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="bg-gray-50 min-h-screen">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
